name: Deploy to Local Runner

on:
  workflow_run:
    workflows: ["GitHub Release"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read version
        id: version
        run: |
          $version = Get-Content version.txt
          echo "VERSION=$version" >> $env:GITHUB_OUTPUT

      - name: Login to DockerHub
        run: |
          docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Pull image
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ermakov-devops:v${{ steps.version.outputs.VERSION }}

      - name: Stop old container if exists
        run: |
          docker stop ermakov-devops || echo "no old container"
          docker rm ermakov-devops || echo "no old container"

      - name: Run new container
        run: |
          docker run -d --name ermakov-devops -p 7245:7245 ${{ secrets.DOCKERHUB_USERNAME }}/ermakov-devops:v${{ steps.version.outputs.VERSION }}
